server {
    listen 80;
    server_name danum.o-r.kr;

    # Redirect HTTP to HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name danum.o-r.kr;

    ssl_certificate /etc/ssl/certificates/certificate.crt;
    ssl_certificate_key /etc/ssl/certificates/private.key;

    access_log /var/log/nginx/nginx.vhost.access.log;
    error_log /var/log/nginx/nginx.vhost.error.log;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://43.203.8.51:8080;
    }
}
